### PR TITLE
Compilation fixes

### PR DESCRIPTION
**Pull request by hmusta**

### CODE REVIEW

**Comment by hmusta** [comment]
This issue only seems to come up when running the main `Makefile`, and not when creating a `build` directory and running `cmake`. So, I have a feeling that running everything through `bash -c` call in the `Makefile` is not passing all environment variables.

**Comment by hmusta** [comment]
This was actually not completed. I tried this out and simply setting `-l` doesn't work.

Also, we need to change the workflow so that it does the compilation using the Makefile instead of cmake

**Comment by karasikov** [comment]
why do we need this Makefile? What's wrong with cmake?

**Comment by karasikov** [comment]
So, anyway. This bug is on the compiler side, so I suggest we just require a more recent version

**Pull request merged**
