### PR TITLE
Test Files for taxonomic classification

### PR DESCRIPTION
**Pull request by heracle**
Add the test files that will be further used inside unit and integration taxonomic tests

### CODE REVIEW

**Review by karasikov — CHANGES_REQUESTED** [review]
add the code too. Otherwise this data is useless

**Comment by heracle** [comment]
Thanks for reviewing my PRs! I am trying to split the code into small pieces and to send them in an order that would make sense. I will add these files in another PR with all the integration tests

**Comment by karasikov** [comment]
I don't see how these files are used. Please merge to the next PR.

**Comment by heracle** [comment]
I will merge them to https://github.com/ratschlab/metagraph/pull/348 , the PR with the CLI and the integration tests. Thanks!

**Comment by heracle** [comment]
closing this after moving the files to https://github.com/ratschlab/metagraph/pull/348

**Pull request closed without merging**
